# This is a basic workflow to help you get started with Actions
name: Elm CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload elm dist files
        env:
          WEBDAV_ROOT: ${{secrets.WEBDAV_ROOT}}
          WEBDAV_USER: ${{secrets.WEBDAV_USER}}
          WEBDAV_PASSWORD: ${{secrets.WEBDAV_PASSWORD}}
        run: |
          echo curl -X MKCOL "$WEBDAV_ROOT/ccs" -u "$WEBDAV_USER:$WEBDAV_PASSWORD"
          echo curl -X MKCOL "$WEBDAV_ROOT/images" -u "$WEBDAV_USER:$WEBDAV_PASSWORD"
          cd $GITHUB_WORKSPACE/elm/dist
          find . -type f -exec echo curl -T {} "$WEBDAV_ROOT/{}" -u "$WEBDAV_USER:$WEBDAV_PASSWORD" \;
